import os
import stripe
from typing import Optional, cast


def get_base_url() -> str:
    """Get the base URL for the application based on environment."""
    vercel_env = os.getenv("VERCEL_ENV")
    if vercel_env == "production":
        return "https://vargasjr.dev"
    elif vercel_env == "preview":
        vercel_url = os.getenv("VERCEL_URL")
        if vercel_url:
            return f"https://{vercel_url}"
    return "http://localhost:3000"


def generate_stripe_checkout_session(
    contact_email: Optional[str] = None,
    contact_full_name: Optional[str] = None,
) -> dict:
    """
    Generate a Stripe checkout session for "Vargas JR Salary" product.
    
    This function creates a Stripe checkout session. The contractor agreement PDF
    will be automatically generated and uploaded by the Stripe webhook handler
    when the checkout is completed.
    
    Args:
        contact_email: Email address of the contact
        contact_full_name: Full name of the contact (currently unused, but available for future use)
    
    Returns:
        Dictionary with 'url' key containing the checkout URL
    
    Raises:
        Exception: If Stripe configuration is missing or API calls fail
    """
    stripe_secret_key = os.getenv("STRIPE_SECRET_KEY")
    if not stripe_secret_key:
        raise Exception("STRIPE_SECRET_KEY environment variable is not set")
    
    stripe.api_key = stripe_secret_key
    
    # Search for the "Vargas JR Salary" product
    products = stripe.Product.search(query='name:"Vargas JR Salary"')
    
    if not products.data:
        raise Exception("Product 'Vargas JR Salary' not found in Stripe")
    
    # Narrow the type for mypy
    product = cast(stripe.Product, products.data[0])
    
    # Get active prices for the product
    prices = stripe.Price.list(product=product.id, active=True)
    
    if not prices.data:
        raise Exception(f"No active prices found for product: {product.id}")
    
    # Narrow the type for mypy
    price = cast(stripe.Price, prices.data[0])
    
    # Get base URL for success/cancel URLs
    base_url = get_base_url()
    
    # Create checkout session
    # Note: The contract PDF will be generated by the webhook handler
    # when checkout.session.completed event is received
    # Note: We don't pass customer_email here to match the existing TypeScript implementation
    session = stripe.checkout.Session.create(
        payment_method_types=["card"],
        line_items=[
            {
                "price": price.id,
                "quantity": 1,
            }
        ],
        mode="subscription",
        success_url=f"{base_url}/thank-you?checkout_session_id={{CHECKOUT_SESSION_ID}}",
        cancel_url=base_url,
    )
    
    return {
        "url": session.url,
        "session_id": session.id,
    }
