name: Apply Devin Knowledge

# on:
#   push:
#     branches: [main]
#     paths:
#       - 'docs/**/*.json'
#       - 'scripts/run-knowledge.ts'
#       - '.github/workflows/apply-knowledge.yaml'
#   pull_request:
#     paths:
#       - 'docs/**/*.json'
#       - 'scripts/run-knowledge.ts'
#       - '.github/workflows/apply-knowledge.yaml'
on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

permissions:
  contents: read
  pull-requests: write

jobs:
  preview-knowledge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npx tsx scripts/conditional-install.ts

      - name: Run knowledge preview
        run: |
          npm run run-knowledge -- --preview > knowledge-preview-full.txt 2>&1
          sed -n '/=== Knowledge changes summary ===/,$p' knowledge-preview-full.txt > knowledge-preview.txt
        env:
          DEVIN_API_TOKEN: ${{ secrets.DEVIN_API_TOKEN }}
          GITHUB_PRIVATE_KEY: ${{ secrets.VARGASJR_GITHUB_PRIVATE_KEY }}

  apply-knowledge:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npx tsx scripts/conditional-install.ts

      - name: Apply knowledge changes
        run: npm run run-knowledge
        env:
          DEVIN_API_TOKEN: ${{ secrets.DEVIN_API_TOKEN }}
