name: create-agent

on:
  workflow_dispatch:
    inputs:
      agent_name:
        description: "Agent name to create (e.g., vargas-jr for production)"
        required: false
        type: string
  workflow_call:
    inputs:
      agent_name:
        description: "Agent name to create"
        required: true
        type: string

jobs:
  create-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Generate cache key
        id: cache-key
        run: |
          CACHE_KEY=$(npx tsx -e "
            import { readFileSync, existsSync } from 'fs';
            import { createHash } from 'crypto';
            const packageLockPath = 'package-lock.json';
            if (!existsSync(packageLockPath)) throw new Error('package-lock.json not found');
            const packageLock = JSON.parse(readFileSync(packageLockPath, 'utf8'));
            const stablePackageLock = { ...packageLock };
            delete stablePackageLock.version;
            delete stablePackageLock.lockfileVersion;
            if (stablePackageLock.packages && stablePackageLock.packages['']) {
              const rootPackage = { ...stablePackageLock.packages[''] };
              delete rootPackage.version;
              stablePackageLock.packages[''] = rootPackage;
            }
            const stableContent = JSON.stringify(stablePackageLock, null, 2);
            console.log(createHash('sha256').update(stableContent).digest('hex').substring(0, 16));
          ")
          echo "cache-key=deps-${{ runner.os }}-${CACHE_KEY}" >> "$GITHUB_OUTPUT"
      - name: Cache dependencies and browsers
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/ms-playwright
          key: ${{ steps.cache-key.outputs.cache-key }}
          restore-keys: |
            deps-${{ runner.os }}-
      - name: Install dependencies
        run: npm install
      - name: Create agent
        run: npm run create-agent -- ${{ inputs.agent_name || github.event.inputs.agent_name || '' }}
        env:
          VELLUM_API_KEY: ${{ secrets.VELLUM_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          GITHUB_PRIVATE_KEY: ${{ secrets.VARGASJR_GITHUB_PRIVATE_KEY }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
