name: create-agent

on:
  workflow_dispatch:
    inputs:
      agent_name:
        description: "Agent name to create (e.g., vargas-jr for production)"
        required: false
        type: string
  workflow_call:
    inputs:
      agent_name:
        description: "Agent name to create"
        required: true
        type: string

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  create-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm run setup
      - name: Create agent
        run: npm run create-agent -- ${{ inputs.agent_name || github.event.inputs.agent_name || '' }}
        env:
          VELLUM_API_KEY: ${{ secrets.VELLUM_API_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          NEON_URL: ${{ secrets.NEON_URL }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          GITHUB_PRIVATE_KEY: ${{ secrets.VARGASJR_GITHUB_PRIVATE_KEY }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
