name: create-production-agent

on:
  workflow_dispatch:
    inputs:
      agent_name:
        description: "Agent name to create (e.g., vargas-jr for production)"
        required: false
        type: string

jobs:
  create-production-agent:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-
      - name: Install dependencies
        run: npm install
      - name: Create production agent
        run: npm run create-agent -- ${{ github.event.inputs.agent_name || '' }}
        env:
          VELLUM_API_KEY: ${{ secrets.VELLUM_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          GITHUB_PRIVATE_KEY: ${{ secrets.VARGASJR_GITHUB_PRIVATE_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
