name: debug-agent

on:
  workflow_dispatch:
    inputs:
      branch_override:
        description: "Override branch detection (optional)"
        required: false
        type: string

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  debug-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm run setup
      - name: Debug agent instance
        run: npm run debug-agent -- ${{ inputs.branch_override || github.ref_name }}
        env:
          AWS_DEFAULT_REGION: us-east-1
          VELLUM_API_KEY: ${{ secrets.VELLUM_API_KEY }}
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          GITHUB_PRIVATE_KEY: ${{ secrets.VARGASJR_GITHUB_PRIVATE_KEY }}
          GITHUB_HEAD_REF: ${{ github.head_ref || github.ref_name }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
