name: Preview Agent

on:
  pull_request:
    types: [closed]

jobs:
  check-preview-agent:
    runs-on: ubuntu-latest
    outputs:
      should-cleanup: ${{ steps.check.outputs.should-cleanup }}
    steps:
      - name: Check if preview agent was created
        id: check
        run: |
          WORKFLOW_RUNS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/ci.yaml/runs?head_sha=${{ github.event.pull_request.head.sha }}&status=completed")
          
          HAS_PREVIEW_AGENT=$(echo "$WORKFLOW_RUNS" | jq -r '.workflow_runs[] | select(.conclusion == "success") | .id' | head -1)
          
          if [ -n "$HAS_PREVIEW_AGENT" ]; then
            echo "should-cleanup=true" >> "$GITHUB_OUTPUT"
            echo "✅ Preview agent was created for this PR, cleanup will run"
          else
            echo "should-cleanup=false" >> "$GITHUB_OUTPUT"
            echo "ℹ️ No preview agent found for this PR, skipping cleanup"
          fi

  cleanup-preview-agent:
    runs-on: ubuntu-latest
    needs: check-preview-agent
    if: needs.check-preview-agent.outputs.should-cleanup == 'true'
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm install
      - name: Cleanup preview agent
        run: npm run cleanup-agent -- --pr ${{ github.event.number }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

  fallback-cleanup:
    runs-on: ubuntu-latest
    needs: check-preview-agent
    if: needs.check-preview-agent.outputs.should-cleanup == 'false'
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm install
      - name: Fallback cleanup check
        continue-on-error: true
        run: |
          echo "🔍 Running fallback cleanup check for PR ${{ github.event.number }}"
          npm run cleanup-agent -- --pr ${{ github.event.number }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
