name: Preview Agent

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  create-preview-agent:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Check if agent artifacts are needed
        id: check_artifacts
        run: |
          CHANGED_FILES=$(gh pr view ${{ github.event.number }} --json files --jq '.files[].path')
          if echo "$CHANGED_FILES" | grep -E '^(agent/|browser/|scripts/|app/|components/|db/)'; then
            echo "needs_agent=true" >> "$GITHUB_OUTPUT"
            echo "Preview agent needed - found changes in agent-related paths"
          else
            echo "needs_agent=false" >> "$GITHUB_OUTPUT"
            echo "Preview agent not needed - no changes in agent-related paths"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        if: steps.check_artifacts.outputs.needs_agent == 'true'
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        if: steps.check_artifacts.outputs.needs_agent == 'true'
        run: npm install
      - name: Create preview agent
        if: steps.check_artifacts.outputs.needs_agent == 'true'
        run: npm run create-agent -- pr-${{ github.event.number }}
        env:
          VELLUM_API_KEY: ${{ secrets.VELLUM_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
  cleanup-preview-agent:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm install
      - name: Cleanup preview agent
        run: npm run cleanup-agent -- --pr ${{ github.event.number }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
