name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-apply.yaml"
      - "scripts/run-terraform.ts"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - preview

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

permissions:
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npx tsx scripts/conditional-install.ts

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Run Terraform Apply
        run: npm run terraform
        env:
          AWS_DEFAULT_REGION: us-east-1
          VERCEL_ENV: production
          SES_WEBHOOK_SECRET: ${{ secrets.SES_WEBHOOK_SECRET }}
